@startuml
'https://plantuml.com/zh/class-diagram
page 1x2
title 旅店管理系统

namespace domain.旅店 {
    class 旅店 <<root>> {}
    class 雇员 <<entity>> {}
    旅店 -- 雇员
}

namespace domain.履约单 {
    class 履约单 <<root>> {}
    履约单 -- 预定
    履约单 -- 旅客
    class 预定 {}
    class 旅客 {}
}


namespace domain.支付 {
    class 支付 <<root>> {}
}

namespace domain.房间 {
    class 房间 <<root>> {}
    class 房门 {}
    class 房门锁 {}
    房间 -- 房门
    房门 -- 房卡
    房门 -- 房门锁
    房间 -- 折扣
    class 折扣 {}
}

namespace domain.用户 {
    class 用户 <<root>> {}

    class 会员卡 {}

    用户 -- 会员卡
}


domain.履约单 -- domain.房间
domain.履约单 -- domain.支付
domain.旅店 - domain.履约单
domain.用户 - domain.履约单


namespace domain.报表 {
    abstract 报表 {}

    class 预定报表 extends 报表 {}

    class 入住报表 extends 报表 {}
}
@enduml