server:
  port: ${PORT:8010}
spring:
  application:
    name: hotel-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/h_hotel}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root_password}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: hotel-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  level:
    org.hibernate: INFO